version: '3'
services:
  serviceregistry:
    image: 'ousmane1999/serviceregistry:0.0.1'
    container_name: serviceregistry
    ports:
      - '8761:8761'
  configserver:
    image: 'ousmane1999/configserver:latest'
    container_name: configserver
    ports:
      - '9296:9296'
    environment:
      - EUREKA_SERVER_ADDRESS:http://serviceregistry:8761/eureka
    depends_on:
      - serviceregistry
  apigateway:
    image: 'ousmane1999/apigateway:latest'
    ports:
      - '9090:9090'
    environment:
      - EUREKA_SERVER_ADDRESS:http://serviceregistry:8761/eureka
      - CONFIG_SERVER_URL=configserver
    depends_on:
      - serviceregistry
  orderservice:
    image: 'ousmane1999/orderservice:0.0.1'
    ports:
      - '8081:8081'
    environment:
      - EUREKA_SERVER_ADDRESS:http://serviceregistry:8761/eureka
      - CONFIG_SERVER_URL=configserver
    depends_on:
      - serviceregistry
  productservice:
    image: 'ousmane1999/productservice:0.0.1'
    ports:
      - '8082:8082'
    environment:
      - EUREKA_SERVER_ADDRESS:http://serviceregistry:8761/eureka
      - CONFIG_SERVER_URL=configserver
    depends_on:
      - serviceregistry
  paymentservice:
    image: 'ousmane1999/paymentservice:0.0.1'
    ports:
      - '8089:8089'
    environment:
      - EUREKA_SERVER_ADDRESS:http://serviceregistry:8761/eureka
      - CONFIG_SERVER_URL=configserver
    depends_on:
      - serviceregistry
