server:
  port: 9000

spring:
  application:
    name: CUSTOMER-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/customerdb
    username: postgres
    password: 831800
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    show-sql: true
  config:
    import: configserver:http://${CONFIG_SERVER_URL:localhost}:9296

