
server:
  port: 8089

spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/paymentdb
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQLDialect
  application:
    name: PAYMENT-SERVICE
  config:
    import: configserver:http://${CONFIG_SERVER_URL:localhost}:9296

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8181/realms/online-shopping-app
# configuration for the eureka client

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}